'use client';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
type Workspace={id:string;name:string};
type Grant={id:string;display_name:string;user_email:string;client_id:string;scopes:string[];risk:'HIGH'|'MEDIUM'|'LOW';summary:string;possible_ai:boolean;assessment_source:string;revoked_at:string|null};
type Scan={id:string;status:string;created_at:string;users_scanned:number;error:string|null};
const badge={HIGH:'border-rose-500/30 bg-rose-500/10 text-rose-300',MEDIUM:'border-amber-500/30 bg-amber-500/10 text-amber-300',LOW:'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'};
export default function Dashboard({email,userId}:{email:string;userId:string}) {
 const router=useRouter(); const [db]=useState(()=>createClient());
 const [workspaces,setWorkspaces]=useState<Workspace[]>([]),[workspaceId,setWorkspaceId]=useState(''),[name,setName]=useState('');
 const [grants,setGrants]=useState<Grant[]>([]),[scan,setScan]=useState<Scan|null>(null),[latest,setLatest]=useState<Scan|null>(null);
 const [billing,setBilling]=useState('inactive'),[owner,setOwner]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 const [query,setQuery]=useState(''),[risk,setRisk]=useState('ALL'),[aiOnly,setAiOnly]=useState(false);
 const [confirm,setConfirm]=useState<Grant|null>(null);
 const loadWorkspaces=useCallback(async()=>{const {data,error}=await db.from('workspaces').select('id,name').order('created_at');if(error) throw error;setWorkspaces(data || []);setWorkspaceId(current=>current || data?.[0]?.id || '');},[db]);
 useEffect(()=>{loadWorkspaces().catch(()=>setMessage('Could not load workspaces.')).finally(()=>setLoading(false));
 const p=new URLSearchParams(window.location.search);if(p.get('google')==='connected')setMessage('Google Workspace connected. You can now run an audit.');if(p.get('google')==='failed')setMessage('Google connection failed. Use a super administrator, grant both Directory permissions, and check configuration.');if(p.get('billing')==='success')setMessage('Checkout finished. Refresh results after the billing webhook is processed.');
 },[loadWorkspaces]);
 const load=useCallback(async()=>{
 if(!workspaceId)return;setLoading(true);
 try {
 const [membership,account,complete,recent]=await Promise.all([
 db.from('workspace_members').select('role').eq('workspace_id',workspaceId).eq('user_id',userId).single(),
 db.from('billing_accounts').select('status').eq('workspace_id',workspaceId).single(),
 db.from('scans').select('*').eq('workspace_id',workspaceId).eq('status','complete').order('created_at',{ascending:false}).limit(1).maybeSingle(),
 db.from('scans').select('*').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(1).maybeSingle()]);
 for(const r of [membership,account,complete,recent])if(r.error)throw r.error;
 setOwner(membership.data?.role==='owner');setBilling(account.data?.status || 'inactive');setScan(complete.data);setLatest(recent.data);
 if(complete.data) {const {data,error}=await db.from('oauth_grants').select('*').eq('workspace_id',workspaceId).eq('scan_id',complete.data.id).order('display_name').limit(501);if(error)throw error;setGrants(data || []);} else setGrants([]);
 } catch {setMessage('Could not refresh this workspace.');} finally {setLoading(false);}
 },[db,workspaceId,userId]);
 useEffect(()=>{setGrants([]);setScan(null);setLatest(null);setOwner(false);setConfirm(null);void load();},[load]);
 async function action(path:string,payload:object,success:string) {
 setBusy(path);setMessage('');
 try { const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error || 'Request failed.');
 if(data.url){window.location.assign(data.url);return;}if(data.id){await loadWorkspaces();setWorkspaceId(data.id);setName('');}else await load();setMessage(success);
 } catch(e) {setMessage(e instanceof Error?e.message:'Request failed.');await load();} finally {setBusy('');setConfirm(null);}
 }
 const active=grants.filter(g=>!g.revoked_at),visible=grants.filter(g=>(risk==='ALL'||g.risk===risk)&&(!aiOnly||g.possible_ai)&&`${g.display_name} ${g.user_email} ${g.client_id}`.toLowerCase().includes(query.toLowerCase()));
 const current=workspaces.find(w=>w.id===workspaceId);
 return <div className="min-h-screen">
 <header className="border-b border-slate-800"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-5"><a href="/" className="text-xl font-bold tracking-tight">◈ ScopeGrip <span className="text-emerald-400">AI</span></a><div className="flex items-center gap-4 text-sm text-slate-400"><span className="hidden sm:inline">{email}</span><button className="secondary" onClick={async()=>{await db.auth.signOut();router.replace('/login');router.refresh();}}>Sign out</button></div></div></header>
 <main className="mx-auto max-w-7xl space-y-7 px-6 py-9">
 <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="mb-2 text-xs uppercase tracking-[.2em] text-emerald-400">Workspace security</p><h1 className="text-3xl font-semibold">See what your apps can access.</h1><p className="mt-3 max-w-xl text-sm text-slate-400">Review permissions, understand exposure, and remove unnecessary access.</p></div>
 {workspaces.length>0&&<label className="text-xs text-slate-400">Workspace<select aria-label="Select workspace" disabled={!!busy||loading} className="input mt-2 min-w-48" value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>}</div>
 <div aria-live="polite">{message&&<p className="rounded-lg border border-slate-700 bg-slate-800/50 p-4 text-sm">{message}</p>}</div>
 {!workspaces.length&&!loading?<section className="panel p-8"><h2 className="text-xl font-semibold">Start with your workspace</h2><p className="mt-3 text-sm text-slate-400">Create a workspace, connect a Google super administrator, then activate the $49 USD/month subscription. Scans send app names and permission scopes to OpenAI for explanation.</p><form className="mt-6 flex max-w-lg gap-3" onSubmit={e=>{e.preventDefault();void action('/api/workspace',{name},'Workspace created.');}}><input aria-label="Workspace name" placeholder="Your company name" className="input" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><button disabled={!!busy} className="btn shrink-0">Create workspace</button></form></section>:null}
 {current&&<>
 <section className="panel flex flex-wrap items-center justify-between gap-4 p-5"><div><h2 className="font-medium">{current.name}</h2><p className="mt-1 text-xs text-slate-400">{owner?'Owner':'Viewer'} · Subscription: {billing} · Up to 50 users</p></div><div className="flex flex-wrap gap-2">
 {owner&&<><button className="secondary" disabled={!!busy||loading} onClick={()=>void action('/api/google/connect',{workspaceId},'')}>Connect Google</button><button className="secondary" disabled={!!busy||loading} onClick={()=>void action(['active','trialing','past_due'].includes(billing)?'/api/stripe/portal':'/api/stripe/checkout',{workspaceId},'')}>{['active','trialing','past_due'].includes(billing)?'Manage billing':'Subscribe · $49/mo'}</button><button className="btn" disabled={!!busy||loading} onClick={()=>void action('/api/workspace/scan',{workspaceId},'Audit complete.')}>{busy==='/api/workspace/scan'?'Auditing…':'Run security audit'}</button></>}
 <button className="secondary" disabled={!!busy||loading} onClick={()=>void load()}>Refresh</button></div></section>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Active app grants',active.length,'text-white'],['High-risk grants',active.filter(g=>g.risk==='HIGH').length,'text-rose-300'],['Possible AI grants',active.filter(g=>g.possible_ai).length,'text-violet-300'],['Users scanned',scan?.users_scanned || 0,'text-emerald-300']].map(([label,value,color])=><div className="panel p-5" key={label}><p className="text-sm text-slate-400">{label}</p><p className={`mt-3 text-4xl font-semibold ${color}`}>{loading?'—':value}</p></div>)}</section>
 <section className="panel overflow-hidden"><div className="border-b border-slate-800 p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-semibold">Third-party app access</h2><p className="text-xs text-slate-400">{scan?`Last complete audit: ${new Date(scan.created_at).toLocaleString()}`:'No completed audit yet'}</p></div>
 {latest&&latest.status!=='complete'&&<p className="mt-3 text-sm text-amber-300">Latest scan: {latest.status}. {latest.error || 'If interrupted, retry after the ten-minute operation lease expires.'} {scan?'Showing the previous complete audit.':''}</p>}
 <div className="mt-5 flex flex-wrap gap-3"><input className="input min-w-48 flex-1" aria-label="Search app grants" placeholder="Search app, user, or client ID…" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input w-auto" aria-label="Filter risk" value={risk} onChange={e=>setRisk(e.target.value)}><option value="ALL">All risk levels</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={aiOnly} onChange={e=>setAiOnly(e.target.checked)}/>Possible AI only</label></div></div>
 {loading?<p className="p-8 text-slate-400">Loading workspace…</p>:!visible.length?<div className="p-12 text-center"><p className="text-lg">{scan?'No matching app grants':'Your first audit starts here'}</p><p className="mt-2 text-sm text-slate-400">{scan?'Adjust filters or run a fresh audit.':'Connect Google, subscribe, and run an audit to see real permissions.'}</p></div>:<div className="divide-y divide-slate-800">{visible.map(g=><article className="p-5 sm:p-6" key={g.id}><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h3 className="break-all font-semibold">{g.display_name}</h3><span className={`rounded border px-2 py-0.5 text-xs ${badge[g.risk]}`}>{g.risk}</span>{g.possible_ai&&<span className="text-xs text-violet-300">Possible AI</span>}{g.revoked_at&&<span className="text-xs text-slate-400">Revoked</span>}</div><p className="mt-1 break-all text-xs text-slate-400">{g.user_email}</p><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">{g.summary}</p><details className="mt-3 text-xs text-slate-400"><summary className="cursor-pointer">View {g.scopes.length} permissions · {g.assessment_source==='openai'?'AI-assisted assessment':'Rule-based fallback'}</summary><p className="mt-3 break-all">Client ID: {g.client_id}</p><ul className="mt-2 space-y-1">{g.scopes.map(s=><li className="break-all" key={s}>{s}</li>)}</ul></details></div>{owner&&<button className="rounded-lg border border-rose-500/30 px-3 py-2 text-sm text-rose-300 hover:bg-rose-500/10" disabled={!!busy||!!g.revoked_at} onClick={()=>setConfirm(g)}>{g.revoked_at?'Access revoked':'Revoke access'}</button>}</div></article>)}</div>}
 </section><p className="text-xs leading-5 text-slate-500">Each grant represents one user’s access to one app. Possible AI is an unverified name-based signal. OAuth grants do not prove app usage, data transfer, or whether an app is approved. Revocation removes the current authorization; it does not prevent future consent or erase previously shared data.</p>
 <details className="text-sm text-slate-400"><summary className="cursor-pointer">Create another workspace</summary><form className="mt-4 flex max-w-lg gap-3" onSubmit={e=>{e.preventDefault();void action('/api/workspace',{name},'Workspace created.');}}><input aria-label="New workspace name" className="input" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><button className="secondary shrink-0" disabled={!!busy}>Create</button></form></details>
 </>}
 </main>
 {confirm&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-6" role="presentation"><section role="alertdialog" aria-modal="true" aria-labelledby="revoke-title" aria-describedby="revoke-description" className="panel max-w-md p-6" onKeyDown={e=>{if(e.key==='Escape'&&!busy)setConfirm(null);if(e.key==='Tab'){const buttons=e.currentTarget.querySelectorAll('button');const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><h2 id="revoke-title" className="text-xl font-semibold">Revoke this app’s access?</h2><p id="revoke-description" className="mt-3 break-words text-sm leading-6 text-slate-300">{confirm.display_name} will lose its current Google authorization for {confirm.user_email}. This may interrupt their work. They may authorize the app again.</p><div className="mt-6 flex justify-end gap-3"><button autoFocus className="secondary" disabled={!!busy} onClick={()=>setConfirm(null)}>Cancel</button><button className="rounded-lg bg-rose-500 px-4 py-2 text-sm font-semibold" disabled={!!busy} onClick={()=>void action('/api/workspace/revoke',{workspaceId,grantId:confirm.id},'Access revoked for this user.')}>{busy?'Revoking…':'Revoke access'}</button></div></section></div>}
 </div>;
}
